# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 8.5.0

notifications:
  email: false

services:
    - mongodb

before_install:
    # Set npm version to 5.3.0
    - npm i -g npm@5.3.0

install:
    # Install Backend Dependencies
    - npm install

before_script:
    # Run db script file to create and populate database
    - mongorestore -d StreamloWebServiceDB ./test/streamloWebserviceTestDB --quiet
  
script:
    # Backend build
    - npm run ci
