# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
  - 8.5.0

notifications:
  email: false

services:
  - mongodb

before_install:
  # Set npm version to 5.3.0
  - npm i -g npm@5.3.0

install:
  # Install Backend Dependencies
  - npm install

before_script:
  # Artificial wait: Known travis issue - https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - sleep 15

script:
  # Backend build
  - npm run ci
