# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 8.5.0

services:
    - mongodb

before_install:
    # Set npm version to 5.3.0
    - npm i -g npm@5.3.0
    # Run db script file to create and populate database
    - mongorestore -d StreamloWebServiceDB ./test/streamloWebserviceTestDB
  
install:
    # Install Backend Dependencies
    - npm install

script:
    # Backend build
    - npm run ci
